service:
  type: LoadBalancer
  port: 80
  nodePort: 30080
  annotations: {}

global:
  storageClass: gp3-csi

persistence:
  enabled: true
  storageClass: gp3-csi
  size: 50Gi

database:
  type: external
  external:
    host: postgres
    port: 5432
    database: harbor
    username: harbor
    password: harbor123

redis:
  enabled: true
  persistence:
    enabled: true
    storageClass: gp3-csi
    size: 8Gi

trivy:
  enabled: true
  storageClass: gp3-csi
  persistence:
    enabled: true
    size: 5Gi

registry:
  enabled: true
  persistence:
    enabled: true
    size: 50Gi
    storageClass: gp3-csi

jobservice:
  enabled: true
  persistence:
    enabled: true
    size: 10Gi
    storageClass: gp3-csi

# Additional PVs for Job Service and Registry
persistence:
  enabled: true
  persistentVolumeClaim:
    registry:
      existingClaim: registry-pvc
    jobservice:
      existingClaim: jobservice-pvc

# External Redis Configuration
externalRedis:
  host: harbor-redis
  port: 6379
  coreDatabaseIndex: 0
  jobserviceDatabaseIndex: 1
  registryDatabaseIndex: 2
  chartmuseumDatabaseIndex: 3
  password: ""

# Core Settings
core:
  cache:
    enabled: true
    store: "redis"
  redis:
    host: harbor-redis
    port: 6379
    password: ""
