apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor-config
data:
  config.yaml: |
    database:
      type: postgres
      host: postgres
      port: 5432
      database: harbor
      username: harbor
      password: harbor123
