apiVersion: v1
kind: PersistentVolume
metadata:
  name: jobservice-pv
  labels:
    app: harbor-jobservice
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3-csi
  hostPath:
    path: /etc/core/app.conf
