apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jobservice-pvc
  namespace: harbor-final
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp3-csi
