apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-pv
  labels:
    app: harbor-registry
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3-csi
  hostPath:
    path: /data/harbor/registry
